// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace repos11.Repository.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddFuncAndSP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFuncAndSP));

        string IMigrationMetadata.Id
        {
            get { return "202212301603445_AddFuncAndSP"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
